language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  # - git clone https://ouaisbrefbams/minishell ../minishell

script:
  - python -m flake8
  - python -m mypy src
  # - ./run
  # - ./run -k echo
